name: "Test flow"

on:
  push:
    branches: ["master"]
    
jobs:
  test-print:
    runs-on: ubuntu-latest
    steps:
    - name: "Setup"
      uses: action/checkout@v2
    - name: "Say hello"
      run: echo "HELLO $PATH"
    
